# Generated by Django 5.2.8 on 2025-11-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.CharField(blank=True, max_length=400)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerRequestQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('surface_type', models.CharField(choices=[('synthetic', 'Synthetic'), ('natural', 'Natural')], default='synthetic', max_length=30)),
                ('pile_height_mm', models.IntegerField(blank=True, null=True)),
                ('infill_type', models.CharField(blank=True, max_length=120)),
                ('infill_depth_mm', models.IntegerField(blank=True, null=True)),
                ('shockpad_present', models.BooleanField(default=False)),
                ('last_replacement_date', models.DateField(blank=True, null=True)),
                ('maintenance_frequency', models.CharField(blank=True, max_length=120)),
                ('surface_condition_rating', models.IntegerField(blank=True, null=True)),
                ('certifications', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('owner_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadras', to='api.ownerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='owner_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.ownerrequest')),
                ('quadra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.ownerrequestquadra')),
            ],
        ),
    ]
