# Generated by Django 5.2.8 on 2025-11-09 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ownerrequest_ownerrequestquadra_ownerrequestimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data', '-hora'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='ownerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitação de proprietário', 'verbose_name_plural': 'Solicitações de proprietários'},
        ),
        migrations.AlterModelOptions(
            name='ownerrequestimage',
            options={'verbose_name': 'Imagem da solicitação', 'verbose_name_plural': 'Imagens da solicitação'},
        ),
        migrations.AlterModelOptions(
            name='ownerrequestquadra',
            options={'verbose_name': 'Quadra da solicitação', 'verbose_name_plural': 'Quadras da solicitação'},
        ),
        migrations.AlterModelOptions(
            name='quadra',
            options={'verbose_name': 'Quadra', 'verbose_name_plural': 'Quadras'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante de pagamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='duracao_minutos',
            field=models.IntegerField(default=60, verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='quadra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api.quadra', verbose_name='Quadra'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_pagamento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de pagamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Anotações do administrador'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='business_address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='business_name',
            field=models.CharField(max_length=255, verbose_name='Nome do estabelecimento'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contato'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone de contato'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ownerrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuário solicitante'),
        ),
        migrations.AlterField(
            model_name='ownerrequestimage',
            name='image',
            field=models.ImageField(upload_to='owner_requests/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='ownerrequestimage',
            name='owner_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.ownerrequest', verbose_name='Solicitação'),
        ),
        migrations.AlterField(
            model_name='ownerrequestimage',
            name='quadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.ownerrequestquadra', verbose_name='Quadra'),
        ),
        migrations.AlterField(
            model_name='ownerrequestimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enviado em'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='capacidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='certifications',
            field=models.CharField(blank=True, max_length=255, verbose_name='Certificações'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='infill_depth_mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Profundidade do enchimento (mm)'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='infill_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tipo de enchimento'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='last_replacement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última substituição'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='maintenance_frequency',
            field=models.CharField(blank=True, max_length=120, verbose_name='Frequência de manutenção'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da quadra'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='owner_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadras', to='api.ownerrequest', verbose_name='Solicitação'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='pile_height_mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura do pelo (mm)'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='shockpad_present',
            field=models.BooleanField(default=False, verbose_name='Possui shockpad'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='surface_condition_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avaliação da superfície'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='surface_type',
            field=models.CharField(choices=[('synthetic', 'Sintética'), ('natural', 'Natural')], default='synthetic', max_length=30, verbose_name='Tipo de superfície'),
        ),
        migrations.AlterField(
            model_name='ownerrequestquadra',
            name='tipo',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='capacidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadras', to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da quadra'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de quadra'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('comum', 'Comum'), ('associado', 'Associado'), ('admin', 'Administrador')], default='comum', max_length=20, verbose_name='Tipo de usuário'),
        ),
    ]
