"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bj6z84k#d(1v%*f#=d)_9&=_)m=*iipbb$!sgt#r-gr&5z9(l&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    # apps padrão
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # terceiros
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',

    # app local
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # CORS deve vir antes do CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    # para suportar tradução/idioma (deve vir depois de SessionMiddleware e antes de CommonMiddleware)
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# ---------- TEMPLATES ----------
# procura templates em BASE_DIR / "templates" (nível do manage.py)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # importante para admin / request em templates
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database (padrão sqlite3)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization / Localização
LANGUAGE_CODE = 'pt-br'                 # português (Brasil)
TIME_ZONE = 'America/Sao_Paulo'        # fuso horário do Brasil
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Onde colocar traduções customizadas (se futuramente criar .po/.mo)
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Idiomas habilitados (pode adicionar mais se quiser)
LANGUAGES = [
    ('pt-br', 'Português (Brasil)'),
]


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# pasta(s) onde você coloca seus arquivos estáticos durante desenvolvimento
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# destino do collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (arquivos enviados pelos usuários)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Configuração DRF (Django REST Framework)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
}

# CORS (permitir requisições do Next.js em dev)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# Modelo de usuário customizado
AUTH_USER_MODEL = "api.Usuario"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'